export const $controller = Symbol("controller")
export const $proxy = Symbol("proxy")
export const $fixtures = Symbol("fixtures")
export const $plugins = Symbol("plugins")
export const $promise = Symbol("promise")
export const $result = Symbol("result")
